repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.45.0
    hooks:
      - id: ruff
        args: ["--fix"]  # Автоматическое исправление ошибок

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint

