[development]
# Реквизиты БД
DB_USER = "postgres"
DB_PASS = "postgres"

# Реквизиты RabbitMQ
RABBITMQ_USER = "guest"
RABBITMQ_PASS = "guest"


[production]
# Реквизиты БД
DB_USER = "postgres"
DB_PASS = "postgres"

# Реквизиты RabbitMQ
RABBITMQ_USER = "guest"
RABBITMQ_PASS = "guest"


[testing]
# Реквизиты БД
TEST_DB_USER = "postgres"
TEST_DB_PASS = "postgres"

# Реквизиты RabbitMQ
TEST_RABBITMQ_USER = "guest"
TEST_RABBITMQ_PASS = "guest"