services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5453:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"  # Порт для RabbitMQ (используется клиентами)
      - "15672:15672" # Порт для RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  redis:
    image: redis/redis-stack:latest
    container_name: redis_container
    restart: always
    ports:
      - "6739:6379"  # Порт для подключения Redis клиентов
      - "8001:8001"  # Порт для Redis Insight (веб-интерфейс)
    networks:
      - app_network
    volumes:
      - redis_data:/data

networks:
  app_network: # Общая сеть для сервисов
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data: