[development]
# Настройки БД
DB_HOST = "localhost"
DB_PORT = 5453
DB_NAME = "parcels"

# Настройки Redis
REDIS_HOST = "localhost"
REDIS_PORT = 6739

# Настройки RabbitMQ
RABBITMQ_HOST = "localhost"
RABBITMQ_PORT = 5672

# Настройки внешнего API
CURRENCY_API_HOST = "https://www.cbr-xml-daily.ru/daily_json.js"
